services:
  - type: web
    name: nephrodetect
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python src/download_data.py && python src/train.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
